import type { DrillDefinition } from "./types";

export const backhandVolley: DrillDefinition = {
  slug: "backhand-volley",
  name: "Backhand Volley",
  category: "volleys",
  difficulty: "beginner",
  description:
    "The backhand volley requires a stable wrist and compact swing across the body. Focus on turning your shoulders, keeping the racket face open, and making contact out in front. The non-dominant hand guides the racket during preparation.",
  shortDescription: "Solid backhand volley with shoulder turn and firm wrist.",
  instructions: [
    "Start in the ready position with both hands on the racket",
    "Turn your shoulders to the backhand side as the ball approaches",
    "Keep the racket head above the wrist — don't let it drop",
    "Step forward with your right foot (for right-handers)",
    "Contact the ball in front of your body with a firm, open racket face",
    "Short follow-through — push through the ball, don't swing",
  ],
  thumbnailEmoji: "\uD83E\uDD3E",
  estimatedDuration: 90,
  phases: [
    {
      name: "Preparation",
      description: "Shoulder turn with compact racket position",
      constraints: [
        {
          joint: "leftElbow",
          min: 70,
          max: 130,
          weight: 1.2,
          label: "Racket Arm Elbow",
          correctionBelow: "Elbow too tight — open your arm a bit",
          correctionAbove: "Bring the racket closer — compact preparation",
        },
        {
          joint: "shoulderRotation",
          min: -25,
          max: 15,
          weight: 1.0,
          label: "Shoulder Turn",
          correctionBelow: "Turn your shoulders more to the backhand side",
          correctionAbove: "Don't over-rotate — keep it compact",
        },
        {
          joint: "rightKnee",
          min: 125,
          max: 160,
          weight: 0.8,
          label: "Front Knee Bend",
          correctionBelow: "Don't bend too deep for a volley",
          correctionAbove: "Bend the front knee — step into the ball",
        },
        {
          joint: "leftShoulder",
          min: 35,
          max: 75,
          weight: 1.0,
          label: "Racket Arm Shoulder",
          correctionBelow: "Raise your racket arm — keep it at chest height",
          correctionAbove: "Don't lift the racket too high",
        },
      ],
    },
    {
      name: "Contact",
      description: "Firm contact in front of the body",
      constraints: [
        {
          joint: "leftElbow",
          min: 115,
          max: 160,
          weight: 1.5,
          label: "Contact Extension",
          correctionBelow: "Extend your arm more — contact out in front",
          correctionAbove: "Don't fully lock the elbow at contact",
        },
        {
          joint: "torsoInclination",
          min: -100,
          max: -72,
          weight: 0.8,
          label: "Body Lean",
          correctionBelow: "Don't lean too far forward",
          correctionAbove: "Lean into the shot more",
        },
        {
          joint: "leftWristHeight",
          min: -0.15,
          max: 0.08,
          weight: 1.0,
          label: "Racket Height",
          correctionBelow: "Racket too high — bring it to chest level",
          correctionAbove: "Keep the racket head up — don't let it drop!",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "bv-shoulder-turn",
      check: (scores) => (scores["Shoulder Turn"] ?? 100) < 55,
      message: "Turn your shoulders to the backhand side!",
      type: "correction",
      priority: 10,
    },
    {
      id: "bv-contact",
      check: (scores) => (scores["Contact Extension"] ?? 100) < 55,
      message: "Extend your arm — contact the ball out in front.",
      type: "correction",
      priority: 9,
    },
    {
      id: "bv-racket-drop",
      check: (scores) => (scores["Racket Height"] ?? 100) < 55,
      message: "Keep the racket head above your wrist!",
      type: "correction",
      priority: 8,
    },
    {
      id: "bv-step",
      check: (scores) => (scores["Front Knee Bend"] ?? 100) < 55,
      message: "Step forward into the backhand volley.",
      type: "correction",
      priority: 6,
    },
  ],
  scoreWeights: {
    "Racket Arm Elbow": 1.2,
    "Shoulder Turn": 1.0,
    "Front Knee Bend": 0.8,
    "Racket Arm Shoulder": 1.0,
    "Contact Extension": 1.5,
    "Body Lean": 0.8,
    "Racket Height": 1.0,
  },
};
