import type { DrillDefinition } from "./types";

export const bandeja: DrillDefinition = {
  slug: "bandeja",
  name: "Bandeja",
  category: "overhead",
  difficulty: "intermediate",
  description:
    "The bandeja is a controlled overhead shot used to neutralize lobs while maintaining your net position. Unlike a smash, the bandeja uses a slicing motion with a continental grip, contacting the ball above and slightly in front of your head with a controlled, sideways follow-through.",
  shortDescription:
    "Controlled overhead slice to neutralize lobs from the net.",
  instructions: [
    "Turn sideways with your non-dominant shoulder pointing at the ball",
    "Raise your racket arm with the elbow high (above shoulder height)",
    "Use your non-dominant hand to track the ball above you",
    "Contact the ball above and slightly in front of your head",
    "Slice under the ball with a controlled swing — not full power",
    "Follow through across your body and recover to ready position",
  ],
  thumbnailEmoji: "\uD83E\uDD4F",
  estimatedDuration: 120,
  phases: [
    {
      name: "Preparation",
      description: "Sideways stance with racket raised overhead",
      constraints: [
        {
          joint: "rightShoulder",
          min: 100,
          max: 155,
          weight: 1.5,
          label: "Racket Arm Lift",
          correctionBelow: "Raise your racket arm higher — elbow above shoulder",
          correctionAbove: "Arm too far back — protect your shoulder, keep it controlled",
        },
        {
          joint: "rightElbow",
          min: 70,
          max: 120,
          weight: 1.2,
          label: "Elbow Bend",
          correctionBelow: "Keep some bend in your elbow during preparation",
          correctionAbove: "Don't keep the arm too straight — bend the elbow",
        },
        {
          joint: "shoulderRotation",
          min: -40,
          max: -5,
          weight: 1.0,
          label: "Shoulder Turn",
          correctionBelow: "Turn sideways more — lead with your non-hitting shoulder",
          correctionAbove: "You're too square — turn sideways",
        },
        {
          joint: "leftShoulder",
          min: 70,
          max: 140,
          weight: 0.8,
          label: "Tracking Hand",
          correctionBelow: "Raise your non-hitting hand to track the ball",
          correctionAbove: "Tracking hand too high — relax it slightly",
        },
      ],
    },
    {
      name: "Contact",
      description: "Contact above head with slice under the ball",
      constraints: [
        {
          joint: "rightElbow",
          min: 130,
          max: 170,
          weight: 1.5,
          label: "Arm Extension at Contact",
          correctionBelow: "Extend your arm more at contact — reach up",
          correctionAbove: "Don't hyperextend — slight bend is fine",
        },
        {
          joint: "rightWristHeight",
          min: -0.4,
          max: -0.12,
          weight: 1.2,
          label: "Contact Height",
          correctionBelow: "You're reaching too high — contact slightly in front",
          correctionAbove: "Contact higher — the ball should be above your head",
        },
        {
          joint: "torsoInclination",
          min: -105,
          max: -75,
          weight: 0.8,
          label: "Body Position",
          correctionBelow: "Don't lean back too much on the bandeja",
          correctionAbove: "Stay slightly upright — don't fall forward",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "bd-arm-up",
      check: (scores) => (scores["Racket Arm Lift"] ?? 100) < 55,
      message: "Get your racket arm up high — elbow above your shoulder!",
      type: "correction",
      priority: 10,
    },
    {
      id: "bd-turn",
      check: (scores) => (scores["Shoulder Turn"] ?? 100) < 55,
      message: "Turn sideways! Lead with your non-dominant shoulder.",
      type: "correction",
      priority: 9,
    },
    {
      id: "bd-contact",
      check: (scores) => (scores["Contact Height"] ?? 100) < 55,
      message: "Contact the ball above your head — reach up!",
      type: "correction",
      priority: 8,
    },
    {
      id: "bd-extend",
      check: (scores) => (scores["Arm Extension at Contact"] ?? 100) < 55,
      message: "Extend your arm at contact — full reach upward.",
      type: "correction",
      priority: 7,
    },
    {
      id: "bd-tracking",
      check: (scores) => (scores["Tracking Hand"] ?? 100) < 50,
      message: "Use your free hand to track the ball above you.",
      type: "info",
      priority: 5,
    },
  ],
  scoreWeights: {
    "Racket Arm Lift": 1.5,
    "Elbow Bend": 1.2,
    "Shoulder Turn": 1.0,
    "Tracking Hand": 0.8,
    "Arm Extension at Contact": 1.5,
    "Contact Height": 1.2,
    "Body Position": 0.8,
  },
};
