import type { DrillDefinition } from "./types";

export const forehandVolley: DrillDefinition = {
  slug: "forehand-volley",
  name: "Forehand Volley",
  category: "volleys",
  difficulty: "beginner",
  description:
    "The forehand volley is one of the most common shots in padel. Learn proper racket positioning, a compact swing with a firm wrist, and stepping into the ball. Focus on the contact point in front of your body and a controlled follow-through.",
  shortDescription: "Compact forehand volley with proper contact point.",
  instructions: [
    "Start in the ready position with the racket at chest height",
    "Step forward with your left foot (for right-handers) as you prepare",
    "Keep your elbow close to your body — compact backswing only",
    "Make contact in front of your body with a firm wrist",
    "Push through the ball — don't swing; it's a punching motion",
    "Follow through short and controlled toward the target",
  ],
  thumbnailEmoji: "\uD83C\uDFBE",
  estimatedDuration: 90,
  phases: [
    {
      name: "Preparation",
      description: "Ready position with racket prepared to the forehand side",
      constraints: [
        {
          joint: "rightElbow",
          min: 70,
          max: 120,
          weight: 1.2,
          label: "Racket Arm Elbow",
          correctionBelow: "Keep your elbow angle more open during preparation",
          correctionAbove: "Bring the racket closer — compact preparation",
        },
        {
          joint: "rightShoulder",
          min: 30,
          max: 70,
          weight: 1.0,
          label: "Shoulder Position",
          correctionBelow: "Raise your racket arm a bit higher",
          correctionAbove: "Don't raise the arm too high for a volley",
        },
        {
          joint: "leftKnee",
          min: 130,
          max: 160,
          weight: 0.8,
          label: "Front Knee Bend",
          correctionBelow: "Don't bend the front knee too deep",
          correctionAbove: "Bend the front knee more — step into the shot",
        },
        {
          joint: "rightKnee",
          min: 140,
          max: 170,
          weight: 0.6,
          label: "Back Knee",
          correctionBelow: "Keep the back leg more extended",
          correctionAbove: "Slight bend in the back knee",
        },
      ],
    },
    {
      name: "Contact",
      description: "Make contact in front of the body with a firm wrist",
      constraints: [
        {
          joint: "rightElbow",
          min: 120,
          max: 165,
          weight: 1.5,
          label: "Contact Arm Extension",
          correctionBelow: "Extend your arm more — contact out in front",
          correctionAbove: "Don't fully lock out your elbow",
        },
        {
          joint: "rightShoulder",
          min: 40,
          max: 80,
          weight: 1.2,
          label: "Shoulder at Contact",
          correctionBelow: "Push your arm forward more at contact",
          correctionAbove: "Don't lift the shoulder too high at contact",
        },
        {
          joint: "torsoInclination",
          min: -100,
          max: -70,
          weight: 0.8,
          label: "Body Lean",
          correctionBelow: "Too much forward lean — stay balanced",
          correctionAbove: "Lean into the shot slightly",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "fv-elbow-close",
      check: (scores) => (scores["Racket Arm Elbow"] ?? 100) < 55,
      message: "Keep your elbow close to your body — compact backswing!",
      type: "correction",
      priority: 10,
    },
    {
      id: "fv-contact-front",
      check: (scores) => (scores["Contact Arm Extension"] ?? 100) < 55,
      message: "Contact the ball out in front of your body!",
      type: "correction",
      priority: 9,
    },
    {
      id: "fv-step-in",
      check: (scores) => (scores["Front Knee Bend"] ?? 100) < 55,
      message: "Step forward into the shot — transfer your weight.",
      type: "correction",
      priority: 7,
    },
    {
      id: "fv-shoulder",
      check: (scores) => (scores["Shoulder Position"] ?? 100) < 50,
      message: "Keep the racket at chest height during preparation.",
      type: "correction",
      priority: 6,
    },
  ],
  scoreWeights: {
    "Racket Arm Elbow": 1.2,
    "Shoulder Position": 1.0,
    "Front Knee Bend": 0.8,
    "Back Knee": 0.6,
    "Contact Arm Extension": 1.5,
    "Shoulder at Contact": 1.2,
    "Body Lean": 0.8,
  },
};
