import type { DrillDefinition } from "./types";

export const smash: DrillDefinition = {
  slug: "smash",
  name: "Smash",
  category: "attack",
  difficulty: "advanced",
  description:
    "The padel smash is the most powerful shot, used to finish points. It requires a full overhead swing with maximum arm extension, explosive leg drive, and committed follow-through. Padel smashes are often aimed at the side wall or back glass to make them unreturnable.",
  shortDescription: "Full-power overhead to finish the point.",
  instructions: [
    "Turn sideways and position yourself under the ball",
    "Load your racket arm fully behind your head — trophy position",
    "Drive up from your legs for power",
    "Reach maximum arm extension at contact — highest point possible",
    "Contact the ball at the highest point above and in front of you",
    "Commit to a full follow-through down and across your body",
    "Aim for the side wall or back glass angles",
  ],
  thumbnailEmoji: "\uD83D\uDCA5",
  estimatedDuration: 120,
  phases: [
    {
      name: "Trophy Position",
      description: "Full loading behind the head with high elbow",
      constraints: [
        {
          joint: "rightShoulder",
          min: 120,
          max: 160,
          weight: 1.5,
          label: "Arm Loaded",
          correctionBelow: "Raise your hitting arm higher — full trophy position",
          correctionAbove: "Too far back — protect your shoulder",
        },
        {
          joint: "rightElbow",
          min: 55,
          max: 105,
          weight: 1.3,
          label: "Elbow Bend",
          correctionBelow: "More bend in the elbow — racket drops behind your head",
          correctionAbove: "Bend the elbow more for power loading",
        },
        {
          joint: "shoulderRotation",
          min: -50,
          max: -8,
          weight: 1.2,
          label: "Body Coil",
          correctionBelow: "Rotate more — coil your body for power",
          correctionAbove: "You're too open — turn your hips and shoulders",
        },
        {
          joint: "leftKnee",
          min: 110,
          max: 155,
          weight: 1.0,
          label: "Leg Drive Ready",
          correctionBelow: "Too low — you need to spring up, not down",
          correctionAbove: "Bend your knees more — load your legs for explosive drive",
        },
        {
          joint: "leftShoulder",
          min: 90,
          max: 160,
          weight: 0.8,
          label: "Tracking Hand",
          correctionBelow: "Point at the ball with your free hand",
          correctionAbove: "Free hand too high — relax it",
        },
      ],
    },
    {
      name: "Maximum Extension",
      description: "Full arm extension at highest contact point",
      constraints: [
        {
          joint: "rightElbow",
          min: 150,
          max: 168,
          weight: 1.8,
          label: "Arm Extension",
          correctionBelow: "Extend your arm more — reach the highest point!",
          correctionAbove: "Don't lock your elbow — keep a micro-bend to prevent hyperextension",
        },
        {
          joint: "rightWristHeight",
          min: -0.5,
          max: -0.15,
          weight: 1.5,
          label: "Contact Height",
          correctionBelow: "You're reaching too far — contact above your head",
          correctionAbove: "Contact higher! Reach for the sky!",
        },
        {
          joint: "rightShoulder",
          min: 140,
          max: 163,
          weight: 1.3,
          label: "Shoulder Lift",
          correctionBelow: "Drive your shoulder up — reach high!",
          correctionAbove: "Too far — protect your shoulder from impingement",
        },
        {
          joint: "torsoInclination",
          min: -110,
          max: -70,
          weight: 0.7,
          label: "Body Angle",
          correctionBelow: "Don't lean too far back",
          correctionAbove: "Slight backward lean is natural for the smash",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "sm-extension",
      check: (scores) => (scores["Arm Extension"] ?? 100) < 55,
      message: "Full arm extension! Reach the highest point possible!",
      type: "correction",
      priority: 10,
    },
    {
      id: "sm-coil",
      check: (scores) => (scores["Body Coil"] ?? 100) < 55,
      message: "Coil your body — rotate shoulders and hips for power!",
      type: "correction",
      priority: 9,
    },
    {
      id: "sm-trophy",
      check: (scores) => (scores["Elbow Bend"] ?? 100) < 55,
      message: "Load the racket behind your head — trophy position!",
      type: "correction",
      priority: 8,
    },
    {
      id: "sm-contact",
      check: (scores) => (scores["Contact Height"] ?? 100) < 55,
      message: "Contact the ball at the highest point — reach up!",
      type: "correction",
      priority: 7,
    },
    {
      id: "sm-legs",
      check: (scores) => (scores["Leg Drive Ready"] ?? 100) < 55,
      message: "Use your legs! Bend and drive up for power.",
      type: "correction",
      priority: 6,
    },
    {
      id: "sm-track",
      check: (scores) => (scores["Tracking Hand"] ?? 100) < 50,
      message: "Track the ball with your free hand for timing.",
      type: "info",
      priority: 4,
    },
    {
      id: "sm-shoulder-danger",
      check: (scores) => (scores["Shoulder Lift"] ?? 100) < 30 || (scores["Arm Loaded"] ?? 100) < 30,
      message: "Shoulder at risk! Don't extend your arm too far behind — rotator cuff danger.",
      type: "warning",
      priority: 16,
    },
    {
      id: "sm-elbow-danger",
      check: (scores) => (scores["Arm Extension"] ?? 100) < 30,
      message: "Elbow hyperextension! Never fully lock the elbow on overhead shots.",
      type: "warning",
      priority: 16,
    },
  ],
  scoreWeights: {
    "Arm Loaded": 1.5,
    "Elbow Bend": 1.3,
    "Body Coil": 1.2,
    "Leg Drive Ready": 1.0,
    "Tracking Hand": 0.8,
    "Arm Extension": 1.8,
    "Contact Height": 1.5,
    "Shoulder Lift": 1.3,
    "Body Angle": 0.7,
  },
};
