import type { DrillDefinition } from "./types";

export const tennisBackhand: DrillDefinition = {
  slug: "tennis-backhand",
  name: "Tennis Backhand",
  category: "groundstroke",
  difficulty: "beginner",
  description:
    "The two-handed backhand provides stability and power while protecting the wrist and elbow. Proper technique uses both arms to share the load, reducing injury risk compared to one-handed backhands.",
  shortDescription: "Two-handed backhand with wrist and elbow protection.",
  instructions: [
    "Start in ready position with both hands on the racket",
    "Turn your hips and shoulders to the backhand side",
    "Take the racket back as a unit — both hands stay connected",
    "Step into the ball with your front foot (right foot for right-handers)",
    "Contact the ball in front of your leading hip",
    "Follow through high — both hands finish above your shoulder",
  ],
  thumbnailEmoji: "\uD83C\uDFBE",
  estimatedDuration: 120,
  phases: [
    {
      name: "Preparation",
      description: "Unit turn with both hands on the racket",
      constraints: [
        {
          joint: "shoulderRotation",
          min: -10,
          max: 35,
          weight: 1.3,
          label: "Shoulder Turn",
          correctionBelow: "You're too closed — open up slightly",
          correctionAbove: "Turn more to the backhand side — full unit turn",
        },
        {
          joint: "leftElbow",
          min: 80,
          max: 140,
          weight: 1.0,
          label: "Lead Arm",
          correctionBelow: "Keep your lead arm relaxed during preparation",
          correctionAbove: "Don't extend too early — coil first",
        },
        {
          joint: "rightKnee",
          min: 120,
          max: 160,
          weight: 0.9,
          label: "Knee Bend",
          correctionBelow: "Don't squat too deep on the backhand side",
          correctionAbove: "Bend your knees — get your hips low",
        },
      ],
    },
    {
      name: "Contact & Follow-Through",
      description: "Two-handed contact in front, high finish",
      constraints: [
        {
          joint: "leftElbow",
          min: 125,
          max: 160,
          weight: 1.5,
          label: "Lead Arm Extension",
          correctionBelow: "Extend your lead arm through the ball",
          correctionAbove: "Don't hyperextend — keep control",
        },
        {
          joint: "leftShoulder",
          min: 50,
          max: 110,
          weight: 1.2,
          label: "Shoulder Drive",
          correctionBelow: "Drive your lead shoulder forward through the ball",
          correctionAbove: "Good rotation — finish high",
        },
        {
          joint: "torsoInclination",
          min: -100,
          max: -72,
          weight: 0.8,
          label: "Body Angle",
          correctionBelow: "Stay balanced — don't fall forward",
          correctionAbove: "Lean slightly into the ball",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "tb-rotation",
      check: (scores) => (scores["Shoulder Turn"] ?? 100) < 55,
      message: "Turn your shoulders to the backhand side — full unit turn!",
      type: "correction",
      priority: 10,
    },
    {
      id: "tb-contact",
      check: (scores) => (scores["Lead Arm Extension"] ?? 100) < 55,
      message: "Extend through the ball — both hands drive forward together!",
      type: "correction",
      priority: 9,
    },
    {
      id: "tb-knees",
      check: (scores) => (scores["Knee Bend"] ?? 100) < 55,
      message: "Bend your knees! Load from the legs on the backhand.",
      type: "correction",
      priority: 7,
    },
    {
      id: "tb-elbow-danger",
      check: (scores) => (scores["Lead Arm Extension"] ?? 100) < 30,
      message: "Elbow under stress — let both arms share the load. Don't force it.",
      type: "warning",
      priority: 15,
    },
  ],
  scoreWeights: {
    "Shoulder Turn": 1.3,
    "Lead Arm": 1.0,
    "Knee Bend": 0.9,
    "Lead Arm Extension": 1.5,
    "Shoulder Drive": 1.2,
    "Body Angle": 0.8,
  },
};
