import type { DrillDefinition } from "./types";

export const tennisForehand: DrillDefinition = {
  slug: "tennis-forehand",
  name: "Tennis Forehand",
  category: "groundstroke",
  difficulty: "beginner",
  description:
    "The forehand is the most used shot in tennis. Proper mechanics protect your elbow and shoulder from the repetitive stress of thousands of shots. Focus on hip rotation for power instead of arming the ball.",
  shortDescription: "Forehand groundstroke with proper rotation and elbow protection.",
  instructions: [
    "Start in ready position with knees bent and racket in front",
    "Turn your shoulders and hips as the ball approaches",
    "Take the racket back with a relaxed arm — don't muscle it",
    "Step into the ball with your front foot",
    "Contact the ball in front of your body, not beside it",
    "Finish with the racket over your opposite shoulder",
  ],
  thumbnailEmoji: "\uD83C\uDFBE",
  estimatedDuration: 120,
  phases: [
    {
      name: "Preparation",
      description: "Shoulder turn and racket take-back",
      constraints: [
        {
          joint: "shoulderRotation",
          min: -40,
          max: -5,
          weight: 1.3,
          label: "Shoulder Turn",
          correctionBelow: "Turn your shoulders more — full unit turn",
          correctionAbove: "Too open — rotate away from the ball",
        },
        {
          joint: "rightElbow",
          min: 80,
          max: 140,
          weight: 1.0,
          label: "Arm Position",
          correctionBelow: "Keep your arm relaxed — don't tuck it in",
          correctionAbove: "Don't extend too early — save it for contact",
        },
        {
          joint: "leftKnee",
          min: 125,
          max: 160,
          weight: 0.9,
          label: "Knee Bend",
          correctionBelow: "Don't squat too deep",
          correctionAbove: "Bend your knees more — get low to the ball",
        },
      ],
    },
    {
      name: "Contact & Follow-Through",
      description: "Contact in front, full follow-through over opposite shoulder",
      constraints: [
        {
          joint: "rightElbow",
          min: 130,
          max: 165,
          weight: 1.5,
          label: "Arm Extension",
          correctionBelow: "Extend your arm through the ball — contact in front!",
          correctionAbove: "Don't hyperextend — keep a slight bend",
        },
        {
          joint: "rightShoulder",
          min: 50,
          max: 120,
          weight: 1.2,
          label: "Shoulder Drive",
          correctionBelow: "Drive your hitting shoulder forward through the ball",
          correctionAbove: "Good follow-through — finish over your shoulder",
        },
        {
          joint: "torsoInclination",
          min: -100,
          max: -70,
          weight: 0.8,
          label: "Body Angle",
          correctionBelow: "Stay upright — don't collapse forward",
          correctionAbove: "Lean into the ball slightly for balance",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "tf-rotation",
      check: (scores) => (scores["Shoulder Turn"] ?? 100) < 55,
      message: "Rotate your shoulders! Power comes from the hips, not the arm.",
      type: "correction",
      priority: 10,
    },
    {
      id: "tf-contact",
      check: (scores) => (scores["Arm Extension"] ?? 100) < 55,
      message: "Contact the ball in front of your body — extend through!",
      type: "correction",
      priority: 9,
    },
    {
      id: "tf-knees",
      check: (scores) => (scores["Knee Bend"] ?? 100) < 55,
      message: "Bend your knees! Get low and drive up into the ball.",
      type: "correction",
      priority: 7,
    },
    {
      id: "tf-elbow-danger",
      check: (scores) => (scores["Arm Extension"] ?? 100) < 30,
      message: "Elbow stress detected — don't arm the ball. Use hip rotation for power.",
      type: "warning",
      priority: 15,
    },
  ],
  scoreWeights: {
    "Shoulder Turn": 1.3,
    "Arm Position": 1.0,
    "Knee Bend": 0.9,
    "Arm Extension": 1.5,
    "Shoulder Drive": 1.2,
    "Body Angle": 0.8,
  },
};
