import type { DrillDefinition } from "./types";

export const tennisServe: DrillDefinition = {
  slug: "tennis-serve",
  name: "Tennis Serve",
  category: "serve",
  difficulty: "intermediate",
  description:
    "The tennis serve is the most important shot — it starts every point. A proper serve requires a full kinetic chain from legs through torso rotation to shoulder, elbow, and wrist. Bad serve mechanics are the #1 cause of shoulder injuries in racket sports.",
  shortDescription: "Full serve motion with shoulder protection focus.",
  instructions: [
    "Start with feet shoulder-width apart, side-on to the baseline",
    "Toss the ball slightly in front and to the right (right-handers)",
    "Drop the racket behind your back — full 'trophy position'",
    "Drive up from your legs and rotate your hips and torso",
    "Extend your arm up to contact — highest reachable point",
    "Pronate your forearm through contact for power and spin",
    "Follow through across your body to decelerate safely",
  ],
  thumbnailEmoji: "\uD83C\uDFBE",
  estimatedDuration: 120,
  phases: [
    {
      name: "Trophy Position",
      description: "Racket loaded behind the back, elbow high",
      constraints: [
        {
          joint: "rightShoulder",
          min: 110,
          max: 160,
          weight: 1.5,
          label: "Shoulder Load",
          correctionBelow: "Raise your elbow higher — full trophy position",
          correctionAbove: "Shoulder too far back — risk of impingement. Keep it controlled",
        },
        {
          joint: "rightElbow",
          min: 60,
          max: 110,
          weight: 1.3,
          label: "Elbow Bend",
          correctionBelow: "Bend your elbow more — racket should drop behind your back",
          correctionAbove: "More elbow bend to load the serve",
        },
        {
          joint: "shoulderRotation",
          min: -45,
          max: -5,
          weight: 1.0,
          label: "Body Rotation",
          correctionBelow: "Rotate sideways more — coil your body",
          correctionAbove: "Too open — turn your shoulders away from the net",
        },
        {
          joint: "leftKnee",
          min: 115,
          max: 155,
          weight: 0.9,
          label: "Leg Drive",
          correctionBelow: "Don't bend too deep — you need to spring up",
          correctionAbove: "Bend your knees more — power comes from the legs",
        },
      ],
    },
    {
      name: "Contact Point",
      description: "Full arm extension at highest reach",
      constraints: [
        {
          joint: "rightElbow",
          min: 150,
          max: 168,
          weight: 1.8,
          label: "Arm Extension",
          correctionBelow: "Extend your arm more — reach the highest point",
          correctionAbove: "Don't lock your elbow — keep a micro-bend",
        },
        {
          joint: "rightShoulder",
          min: 140,
          max: 163,
          weight: 1.3,
          label: "Shoulder Reach",
          correctionBelow: "Drive your shoulder up — reach high!",
          correctionAbove: "Too far — protect your shoulder from impingement",
        },
        {
          joint: "torsoInclination",
          min: -105,
          max: -72,
          weight: 0.8,
          label: "Body Angle",
          correctionBelow: "Don't lean back too far — risk to lower back",
          correctionAbove: "Slight lean back is natural — maintain balance",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "ts-trophy",
      check: (scores) => (scores["Shoulder Load"] ?? 100) < 55,
      message: "Full trophy position! Elbow high, racket behind your back.",
      type: "correction",
      priority: 10,
    },
    {
      id: "ts-legs",
      check: (scores) => (scores["Leg Drive"] ?? 100) < 55,
      message: "Use your legs! Bend and drive up for power.",
      type: "correction",
      priority: 9,
    },
    {
      id: "ts-extension",
      check: (scores) => (scores["Arm Extension"] ?? 100) < 55,
      message: "Extend fully at contact — reach the highest point!",
      type: "correction",
      priority: 8,
    },
    {
      id: "ts-rotation",
      check: (scores) => (scores["Body Rotation"] ?? 100) < 55,
      message: "Rotate your body — power comes from the kinetic chain!",
      type: "correction",
      priority: 7,
    },
    {
      id: "ts-shoulder-danger",
      check: (scores) => (scores["Shoulder Reach"] ?? 100) < 30 || (scores["Shoulder Load"] ?? 100) < 30,
      message: "Shoulder at risk! Don't overextend — protect the rotator cuff.",
      type: "warning",
      priority: 16,
    },
  ],
  scoreWeights: {
    "Shoulder Load": 1.5,
    "Elbow Bend": 1.3,
    "Body Rotation": 1.0,
    "Leg Drive": 0.9,
    "Arm Extension": 1.8,
    "Shoulder Reach": 1.3,
    "Body Angle": 0.8,
  },
};
