import type { DrillDefinition } from "./types";

export const vibora: DrillDefinition = {
  slug: "vibora",
  name: "Vibora",
  category: "attack",
  difficulty: "advanced",
  description:
    "The vibora is an aggressive overhead shot similar to the bandeja but with added wrist snap and topspin/sidespin. It is hit with more power and a pronounced wrist pronation to create a venomous spin that makes the ball kick off the side wall. The preparation is similar to the bandeja but the swing is more aggressive.",
  shortDescription:
    "Aggressive overhead with wrist snap for venomous spin.",
  instructions: [
    "Turn fully sideways — even more than a bandeja",
    "Load the racket behind your head with a high elbow",
    "Point at the ball with your non-hitting hand for timing",
    "Snap your wrist aggressively through contact for spin",
    "Contact slightly in front and to the side of your head",
    "Pronate your forearm through the ball — feel the spin",
    "Follow through more aggressively than a bandeja",
  ],
  thumbnailEmoji: "\uD83D\uDC0D",
  estimatedDuration: 120,
  phases: [
    {
      name: "Loading",
      description: "Deep turn with racket loaded behind the head",
      constraints: [
        {
          joint: "rightShoulder",
          min: 110,
          max: 158,
          weight: 1.5,
          label: "Arm Lift",
          correctionBelow: "Get your racket arm higher — load it behind your head",
          correctionAbove: "Too high — protect your shoulder. Keep it controlled",
        },
        {
          joint: "rightElbow",
          min: 60,
          max: 110,
          weight: 1.3,
          label: "Elbow Load",
          correctionBelow: "Bend the elbow more — racket drops behind the head",
          correctionAbove: "Bend your elbow more to load the swing",
        },
        {
          joint: "shoulderRotation",
          min: -50,
          max: -10,
          weight: 1.2,
          label: "Body Rotation",
          correctionBelow: "Rotate your body more — full sideways turn",
          correctionAbove: "You're too open — turn sideways more",
        },
        {
          joint: "leftShoulder",
          min: 80,
          max: 150,
          weight: 0.8,
          label: "Tracking Arm",
          correctionBelow: "Point at the ball with your free hand",
          correctionAbove: "Free hand too high — relax slightly",
        },
        {
          joint: "leftKnee",
          min: 120,
          max: 160,
          weight: 0.7,
          label: "Leg Load",
          correctionBelow: "Don't squat too deep",
          correctionAbove: "Bend your legs more to load power from the ground",
        },
      ],
    },
    {
      name: "Strike",
      description: "Aggressive wrist snap through the ball",
      constraints: [
        {
          joint: "rightElbow",
          min: 140,
          max: 165,
          weight: 1.5,
          label: "Strike Extension",
          correctionBelow: "Extend your arm fully through the strike",
          correctionAbove: "Don't hyperextend — keep a slight bend to protect your elbow",
        },
        {
          joint: "rightWristHeight",
          min: -0.45,
          max: -0.1,
          weight: 1.3,
          label: "Contact Height",
          correctionBelow: "Don't reach too high — slight forward angle",
          correctionAbove: "Contact higher — above your head!",
        },
        {
          joint: "torsoInclination",
          min: -100,
          max: -68,
          weight: 0.8,
          label: "Body Angle",
          correctionBelow: "Don't lean too far back",
          correctionAbove: "Stay balanced — slight lean back is fine",
        },
      ],
    },
  ],
  feedbackRules: [
    {
      id: "vb-rotation",
      check: (scores) => (scores["Body Rotation"] ?? 100) < 55,
      message: "Full sideways turn! More rotation than a bandeja.",
      type: "correction",
      priority: 10,
    },
    {
      id: "vb-load",
      check: (scores) => (scores["Elbow Load"] ?? 100) < 55,
      message: "Load the racket behind your head — deep elbow bend!",
      type: "correction",
      priority: 9,
    },
    {
      id: "vb-extension",
      check: (scores) => (scores["Strike Extension"] ?? 100) < 55,
      message: "Extend fully through the ball — snap the wrist!",
      type: "correction",
      priority: 8,
    },
    {
      id: "vb-height",
      check: (scores) => (scores["Contact Height"] ?? 100) < 55,
      message: "Contact above your head — reach up for the ball!",
      type: "correction",
      priority: 7,
    },
    {
      id: "vb-tracking",
      check: (scores) => (scores["Tracking Arm"] ?? 100) < 50,
      message: "Point at the ball with your free hand for timing.",
      type: "info",
      priority: 5,
    },
    {
      id: "vb-shoulder-danger",
      check: (scores) => (scores["Arm Lift"] ?? 100) < 30,
      message: "Shoulder at risk! Reduce arm extension to protect the rotator cuff.",
      type: "warning",
      priority: 15,
    },
    {
      id: "vb-elbow-danger",
      check: (scores) => (scores["Strike Extension"] ?? 100) < 30,
      message: "Elbow hyperextension detected! Keep a slight bend at contact.",
      type: "warning",
      priority: 15,
    },
  ],
  scoreWeights: {
    "Arm Lift": 1.5,
    "Elbow Load": 1.3,
    "Body Rotation": 1.2,
    "Tracking Arm": 0.8,
    "Leg Load": 0.7,
    "Strike Extension": 1.5,
    "Contact Height": 1.3,
    "Body Angle": 0.8,
  },
};
